index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'welcome'
        permanent: true
    requirements: 
        _locale: en|fr
